Implement rule description parsing from MS Learn
kysect/Configuin pull request #13
Opened 2023-07-30 22:31 UTC by FrediKats

Close #5 
Реализовал парсинг основной части рулов. Оставил пачку TODO по мотивам которых заведу ишуи после мёрджа.

2023-08-01 11:27 UTC, Bibletoon requested changes

2023-08-01 11:27 UTC, Bibletoon commented on Sources/Kysect.Configuin.Core/MarkdownParsing/Documents/MarkdownDocumentParser.cs
> +    }
Лукс лайк парсер опять занимается созданием каких-то средних между маркдауном и доменом моделек, как было с таблицами

2023-08-01 11:27 UTC, Bibletoon commented on Sources/Kysect.Configuin.Core/MarkdownParsing/Tables/Models/MarkdownTableContent.cs
> +﻿namespace Kysect.Configuin.Core.MarkdownParsing.Tables.Models;
Возможно оффтоп и надо было раньше писать, но бросилось в глаза только сейчас: мне не нравится идея с проектом "Core" просто как сама концепция. Сейчас там маркдаун парсеры лежат, потом штуки для обработки правил и генерации документации добавятся, потом ещё бог знает что заедет и уже не разберёшься что такое ядро, так что предлагаю как-то пойти в сторону декомпозиции одного "Core" проекта на более осмысленные. Возможно не в этом пулл реквесте, но as soon as possible

2023-08-01 11:27 UTC, Bibletoon commented on Sources/Kysect.Configuin.Core/MsLearnDocumentation/IMsLearnDocumentationParser.cs
> +    RoslynStyleRule ParseStyleRule(string info);
Не понял почему оно тут появилось Есть какая-то потребность отдельно доставать StyleRule напрямую из стринги? А откуда она появилась?

Если это только для того, чтобы протестировать что стайл рулы достаются нормально, то добавление этого в абстракцию выглядит максимально странно

2023-08-01 14:01 UTC, FrediKats commented on Sources/Kysect.Configuin.Core/MarkdownParsing/Tables/Models/MarkdownTableContent.cs
> +﻿namespace Kysect.Configuin.Core.MarkdownParsing.Tables.Models;
https://github.com/kysect/Configuin/issues/14

2023-08-02 06:05 UTC, Bibletoon approved these changes
В целом ок, по поводу создания документа конечно есть скрытые подсознательные опасения, но не знаю насколько они оправданы.

2023-08-02 06:05 UTC, Bibletoon commented on Sources/Kysect.Configuin.Core/MsLearnDocumentation/Tables/Models/MsLearnPropertyValueDescriptionTable.cs
> +            throw new ConfiguinException($"Table contains more that one value for property {key}");
Сообщение у ошибки не очень, ситуация когда у проперти несколько значений вполне валидная же, ошибка когда в таблице нет проперти которую мы хотим получить

2023-08-02 10:47 UTC, annchous approved these changes

2023-08-02 10:47 UTC, annchous commented on Sources/Kysect.Configuin.Core/RoslynRuleModels/RoslynStyleRuleOptionValue.cs
> +public record RoslynStyleRuleOptionValue(string Value, string Description);
RoslynStyleRule как-то длинновато звучит и смешивается со второй половиной названия. Нет других идей по неймингу?

2023-08-02 10:47 UTC, annchous commented on Sources/Kysect.Configuin.Core/MsLearnDocumentation/Tables/Models/MsLearnPropertyValueDescriptionTable.cs
> +            throw new ConfiguinException($"Table contains more that one value for property {key}");
*than ?

2023-08-02 10:47 UTC, annchous commented on Sources/Kysect.Configuin.Core/MsLearnDocumentation/Tables/Models/MsLearnPropertyValueDescriptionTable.cs
> +            throw new ConfiguinException($"Table contains more that one value for property {key}");
+ если будет 0, то текст ошибки не очень правильный, но это не критично.

2023-08-02 11:52 UTC, Bibletoon commented on Sources/Kysect.Configuin.Core/RoslynRuleModels/RoslynStyleRuleOptionValue.cs
> +public record RoslynStyleRuleOptionValue(string Value, string Description);
Мне кажется тут можно вполне отдельный пр придумать на сокращение имён половины классов, так как много где ну очень длинные имена выходят

2023-08-03 07:32 UTC, Bibletoon commented on Sources/Kysect.Configuin.Tests/MsLearnDocumentation/MsLearnDocumentationParserTests.cs
> +        var expectedOptions = new RoslynStyleRuleOption(
Переменная почему-то не используется

2023-08-04 07:28 UTC, merged